---
 - postgresql_user:
     login_host: "{{ ansible_default_ipv4.address }}"
     login_user: "{{ user_conn }}"
     login_password: "{{ pwd_conn }}"
     encrypted: yes
     name: "{{ item.username }}"
     password: "{{ item.pwd }}"
   with_items: "{{ list_user }}"
 - name: write userlist
   shell: "psql -AtXF' ' -U postgres -c 'select rolname, rolpassword from pg_authid' |sed -e 's:^:\":' -e 's:$:\":' -e 's: :\" \":' -e '1,5d' > /etc/pgbouncer/userlist.txt"
